name: Compare functions
on: push
jobs:
  compare:
    if: ${{github.actor == 'octocat'}}
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{contains('Hello', 'ell')}}
          STARTS_WITH: ${{startsWith('Hello', 'He')}}
          END_WITH: ${{endsWith('Hello', 'lo')}}
