name: GITHUB_OUTPUT
on: push
jobs:
  share:
    if: ${{github.actor == 'octocat'}}
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{steps.source.outputs.result}}
        run: echo "${RESULT}"
