name: Hash functions
on: push
jobs:
  hash:
    if: ${{github.actor == 'octocat'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${HASH}"
        env:
          HASH: ${{hashFiles('.github/workflows/*.yml')}}
