name: Secrets
on: push
jobs:
  print:
    if: ${{github.actor == 'octocat'}}
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
